secrets:
  catalog_config_secret:
    external: true

networks:
  shared-net:
    external: true

services:
  fc-mongodb:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    volumes:
      - /srv/data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "wake"
      MONGO_INITDB_ROOT_PASSWORD: "VERY_SECRET_PASSWORD"
    networks:
      - shared-net

  federated-catalog:
    image: federated-catalog-local:latest
    depends_on:
      - fc-mongodb
    ports:
      - "39191:39191"
      - "39193:39193"
      - "39194:39194"
      - "39195:39195"
    secrets:
      - catalog_config_secret
    networks:
      - shared-net

    entrypoint: [
      "java",
      "-Dedc.fs.config=/run/secrets/catalog_config_secret",
      "-jar", "/federated-catalog.jar",
      "--log-level=DEBUG"
    ]
