services:

  provider-base-vault:
    image: hashicorp/vault
    container_name: provider-base-vault
    ports:
      - "8301:8201"
      - "8300:8200/tcp"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK  # Lock memory to prevent sensitive data from swapping to disk
    volumes:
      - ./file:/vault/file:rw
      - ./logs:/vault/logs:rw
      - ./tmp:/vault/tmp:rw
      - ./config:/vault/config:r
      - ./secrets:/vault/secrets:r
    entrypoint: vault server -config=/vault/config/config.hcl
    networks:
      - base-ds-network

networks:
  base-ds-network:
    name: base-ds-network
    driver: bridge

