/*
 *  Copyright (c) 2025 Universidad de Alicante
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Apache License, Version 2.0 which is available at
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Contributors:
 *       MO - Universidad de Alicante - initial implementation
 *
 */

package org.eclipse.edc.identity.extension;
import org.eclipse.edc.spi.iam.ClaimToken;
import org.eclipse.edc.spi.iam.IdentityService;
import org.eclipse.edc.spi.iam.TokenParameters;
import org.eclipse.edc.spi.iam.TokenRepresentation;
import org.eclipse.edc.spi.iam.VerificationContext;
import org.eclipse.edc.spi.result.Result;
import org.eclipse.edc.spi.types.TypeManager;

import java.util.Map;

/**
 * The {@code IamIdentityService} class is an implementation of the {@link IdentityService} interface
 * responsible for managing identity-related operations such as obtaining client credentials
 * and verifying JWT tokens.
 *
 * This service utilizes a {@link TypeManager} for serialization and deserialization purposes
 * and operates based on predefined claims, a client identifier, and signed claims.
 */
public class IamIdentityService implements IdentityService {

    /**
     * Manages type-related operations and provides serialization and deserialization capabilities
     * for converting objects to and from various formats. This class is responsible for handling
     * type mappings, object conversions, and other type-related functionalities necessary for the
     * operation of the {@link IamIdentityService}.
     *
     * Used primarily to enable operations that involve processing and managing structured data, such
     * as claims, and to facilitate the handling of identity-related operations in the IAM context.
     *
     * The {@code typeManager} is initialized during the extension startup and is shared
     * across components to ensure consistent data mapping and type transformation.
     */
    private final TypeManager typeManager;

    /**
     * Represents the unique identifier for the client associated with the identity service.
     * This value is used to distinguish and identify a specific participant or client
     * within the IAM (Identity and Access Management) system.
     *
     * It is typically assigned during the initialization of the {@code IamIdentityService}
     * instance and remains immutable for the lifetime of the object.
     */
    private final String clientId;

    /**
     * A map containing identity claims represented as key-value pairs.
     * Claims provide information about an identity, such as attributes or assertions,
     * which can be used for authentication, authorization, or identity verification.
     * The keys in the map are strings representing the claim names, and the values are
     * objects representing the corresponding claim values.
     *
     * This variable is used to store and manage claims that relate to the identity of
     * a participant within the system.
     */
    Map<String, Object> claims;

    /**
     * Represents a string containing signed claims used for identity verification
     * and authentication purposes. The value is generated by signing a set of
     * claims with a private key, ensuring the integrity and authenticity of the
     * claims data.
     *
     * This variable is utilized within the identity service implementation to enable
     * secure transmission and validation of participant information in the system.
     */
    String signedClaims;


    /**
     * Constructs an instance of {@code IamIdentityService}.
     *
     * @param typeManager the {@link TypeManager} used for handling type transformations
     * @param claims a map containing claims associated with the identity
     * @param clientId the identifier of the client being represented
     * @param signedClaims a string representation of the signed claims
     */
    public IamIdentityService(TypeManager typeManager,
                              Map<String, Object> claims,
                              String clientId, String signedClaims) {
        this.typeManager = typeManager;
        this.clientId = clientId;
        this.claims = claims;
        this.signedClaims = signedClaims;
    }


    /**
     * Generates and returns a client credentials token representation based on the provided token parameters.
     *
     * @param parameters The {@link TokenParameters} containing the required claims for generating the token.
     *                   Must include an "aud" claim representing the audience of the token.
     * @return A {@link Result} containing the generated {@link TokenRepresentation} if successful,
     *         or an error result if the operation fails.
     */
    @Override
    public Result<TokenRepresentation> obtainClientCredentials(TokenParameters parameters) {
        var token = new Token();
        token.setAudience(parameters.getStringClaim("aud"));
        token.setClientId(clientId);
        token.setClaims(claims);
        token.setSignedClaims(signedClaims);


        TokenRepresentation tokenRepresentation = TokenRepresentation.Builder.newInstance()
                .token(typeManager.writeValueAsString(token))
                .build();

        return Result.success(tokenRepresentation);
    }

    /**
     * Verifies the provided JWT token and extracts relevant claims to construct a {@link ClaimToken}.
     *
     * @param tokenRepresentation the representation of the token to be verified
     * @param context the verification context containing additional data required for token verification
     * @return a {@link Result} containing a {@link ClaimToken} if the verification is successful
     */
    @Override
    public Result<ClaimToken> verifyJwtToken(TokenRepresentation tokenRepresentation, VerificationContext context) {
        var token = typeManager.readValue(tokenRepresentation.getToken(), Token.class);

        return Result.success(
                ClaimToken.Builder.newInstance()
                        .claim("client_id", token.clientId)
                        .claim("claims", token.getClaims())
                        .claim("signedClaims", token.getSignedClaims())
                        .build()
        );
    }

    private static class Token {
        private String audience;
        private Map<String, Object> claims;
        private String clientId;
        private String signedClaims;

        public String getClientId() {
            return clientId;
        }

        public void setClientId(String clientId) {
            this.clientId = clientId;
        }

        public String getAudience() {
            return audience;
        }

        public void setAudience(String audience) {
            this.audience = audience;
        }

        public Map<String, Object> getClaims() {
            return claims;
        }

        public void setClaims(Map<String, Object> claims) {
            this.claims = claims;
        }

        public String getSignedClaims() {
            return signedClaims;
        }

        public void setSignedClaims(String signedClaims) {
            this.signedClaims = signedClaims;
        }


    }
}
